from decouple import config, Csv
import json

# MongoDB
MONGO_HOST = config("MONGO_HOST")
MONGO_PORT = config("MONGO_PORT", cast=int)
MONGO_USERNAME = config("MONGO_USERNAME")
MONGO_PASSWORD = config("MONGO_PASSWORD")

# Webpages
PAGE_DEPTH_RANGE = config("PAGE_DEPTH_RANGE", default="0.14,0.17", cast=Csv(float))

# ADS
AD_PROVIDER = config("AD_PROVIDER")
AD_CLICK_PROBABILITY_RANGE = config(
    "AD_CLICK_PROBABILITY_RANGE", default="0.32,0.40", cast=Csv(float)
)
AD_KEYWORDS = config("AD_KEYWORDS", cast=Csv())
AD_KEYWORDS_SMARTPHONE = config("AD_KEYWORDS_SMARTPHONE", cast=Csv(), default=[])
AD_KEYWORDS_CLICK_PROBABILITY_RANGE = config(
    "AD_KEYWORDS_CLICK_PROBABILITY_RANGE", cast=Csv(float), default="0.74,0.87"
)
AD_TYPES = {
    "vignette": config("VIGNETTE_AD_TYPE", default=0.8, cast=float),
    "in_page": config("IN_PAGE_AD_TYPE", default=0.2, cast=float),
}

# Proxy
SMARTPROXY_HOST = config("SMARTPROXY_HOST")
SMARTPROXY_PORT = config("SMARTPROXY_PORT", cast=int)

DATAIMPULSE_HOST = config("DATAIMPULSE_HOST")
DATAIMPULSE_PORT = config("DATAIMPULSE_PORT", cast=int)

# Links
PAGE_CONTENT_ELEMENT = config("PAGE_CONTENT_ELEMENT")
RELATED_ARTICLES_ELEMENTS = config("RELATED_ARTICLES_ELEMENTS")
PAGE_CLICKS_MIN = config("PAGE_CLICKS_MIN", cast=int)
PAGE_CLICKS_MAX = config("PAGE_CLICKS_MAX", cast=int)
VIGNETTE_CLOSE_AD_ELEMENTS = config("VIGNETTE_CLOSE_AD_ELEMENTS")
VIGNETTE_OPEN_AD_ELEMENTS = config("VIGNETTE_OPEN_AD_ELEMENTS")
IN_PAGE_OPEN_AD_LINK_ELEMENTS = config("IN_PAGE_OPEN_AD_LINK_ELEMENTS")
MAXIMUM_NO_OF_ADS = config("MAXIMUM_NO_OF_ADS", cast=int)
PROXY_DOMAIN_WHITELISTS = config("PROXY_DOMAIN_WHITELISTS", cast=Csv())
