name: Deploy ish-bot-identities with Gunicorn, Nginx, and SSL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Upload code to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_DOMAIN }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "./"
        target: "~/ish-bot-identities"
        rm: true
        exclude: |
          .git

    - name: Set up Gunicorn, Nginx, and SSL
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_DOMAIN }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          sudo apt-get update
          sudo apt-get install -y nginx python3-venv

          # Move project directory and set up virtual environment
          sudo rm -r /var/www/ish-bot-identities
          sudo mv ~/ish-bot-identities /var/www/
          
          python3 -m venv /var/www/ish-bot-identities/.venv
          source /var/www/ish-bot-identities/.venv/bin/activate
          pip install --upgrade pip
          pip install -r /var/www/ish-bot-identities/requirements.txt
          pip install gunicorn
          sudo tee /var/www/ish-bot-identities/.env <<EOF
          # MongoDB
          MONGO_HOST=${{ secrets.MONGO_HOST }}
          MONGO_PORT=${{ secrets.MONGO_PORT }}
          MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}

          # Webpages
          PAGE_DEPTH_RANGE=0.14,0.17

          # ADS
          AD_PROVIDER=monetag
          AD_CLICK_PROBABILITY_RANGE=0.32,0.40
          AD_KEYWORDS=win,gamble,casino,money,bet,\$,cash,virus,hack,stock,forex,crypto
          AD_KEYWORDS_SMARTPHONE=
          AD_KEYWORDS_CLICK_PROBABILITY_RANGE=0.74,0.87

          VIGNETTE_AD_TYPE=0.8
          IN_PAGE_AD_TYPE=0.2

          # Proxy
          SMARTPROXY_HOST=gate.smartproxy.com
          SMARTPROXY_PORT=7000
          EOF
          
          # Set up Nginx
          sudo systemctl start nginx
          sudo systemctl enable nginx

          # Remove old Gunicorn service and configure a new one
          sudo systemctl stop gunicorn
          sudo rm /etc/systemd/system/gunicorn.service
          
          sudo tee /etc/systemd/system/gunicorn.service <<EOF
          [Unit]
          Description=Gunicorn instance to serve ish-bot-identities
          After=network.target

          [Service]
          User=${{ secrets.SERVER_USER }}
          Group=www-data
          WorkingDirectory=/var/www/ish-bot-identities
          Environment="PATH=/var/www/ish-bot-identities/.venv/bin"
          ExecStart=/var/www/ish-bot-identities/.venv/bin/gunicorn --workers 3 --bind unix:/var/www/ish-bot-identities/ish_bot.sock --log-level=info flaskr:app

          EnvironmentFile=/var/www/ish-bot-identities/.env  # Load .env file

          [Install]
          WantedBy=multi-user.target
          EOF

          sudo systemctl daemon-reload
          sudo systemctl start gunicorn
          sudo systemctl enable gunicorn

          # Set up Nginx server configuration
          sudo tee /etc/nginx/sites-available/ish-bot-identities <<EOF
          server {
              listen 80;
              server_name ${{ secrets.SERVER_DOMAIN }};

              location / {
                  include proxy_params;
                  proxy_pass http://unix:/var/www/ish-bot-identities/ish_bot.sock;
              }

              location /static/ {
                  alias /var/www/ish-bot-identities/static/;
              }
          }
          EOF

          sudo ln -sf /etc/nginx/sites-available/ish-bot-identities /etc/nginx/sites-enabled
          sudo nginx -t
          sudo systemctl restart nginx
